"""
Utility functions and helpers for DaVinci Resolve MCP Server.
"""

from .exceptions import (
    AudioProcessingError,
    ColorGradingError,
    ConfigurationError,
    DaVinciResolveMCPError,
    EnvironmentError,
    InsufficientPermissionsError,
    MediaImportError,
    MediaPoolError,
    OperationTimeoutError,
    ProjectNotFoundError,
    ProjectOperationError,
    RenderError,
    RenderQueueError,
    ResolveAPIError,
    ResolveConnectionError,
    ResolveNotRunningError,
    ResourceNotAvailableError,
    TimelineError,
    TimelineNotFoundError,
    UnsupportedFormatError,
    ValidationError,
)
from .helpers import (
    create_temp_file,
    ensure_directory_exists,
    format_duration,
    get_file_extension,
    is_supported_audio_format,
    is_supported_video_format,
    sanitize_filename,
    validate_file_path,
    validate_frame_rate,
    validate_resolution,
)

__all__ = [
    "AudioProcessingError",
    "ColorGradingError",
    "ConfigurationError",
    # Exceptions
    "DaVinciResolveMCPError",
    "EnvironmentError",
    "InsufficientPermissionsError",
    "MediaImportError",
    "MediaPoolError",
    "OperationTimeoutError",
    "ProjectNotFoundError",
    "ProjectOperationError",
    "RenderError",
    "RenderQueueError",
    "ResolveAPIError",
    "ResolveConnectionError",
    "ResolveNotRunningError",
    "ResourceNotAvailableError",
    "TimelineError",
    "TimelineNotFoundError",
    "UnsupportedFormatError",
    "ValidationError",
    "create_temp_file",
    "ensure_directory_exists",
    "format_duration",
    "get_file_extension",
    "is_supported_audio_format",
    "is_supported_video_format",
    "sanitize_filename",
    # Helpers
    "validate_file_path",
    "validate_frame_rate",
    "validate_resolution",
]
